# Uncomment the next line to define a global platform for your project
# platform :ios, '12.4'
use_frameworks!

target 'CashFlowGame' do
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for CashFlowGame
  pod 'SnapKit'
  pod 'Kingfisher'
end
